config/routes.rb
Rails.application.routes.draw do

  root 'choropleth#view'

  post '/indices/min_max', to: 'indices#min_max'

  post '/state_records', to: 'state_records#get_record'

  get '/explanation', to: 'explanation#show'

end

app/models/adjacency.rb
class Adjacency < ActiveRecord::Base
	belongs_to :parent, class_name: "StateRecord"
	belongs_to :child, class_name: "StateRecord"
end

app/models/index.rb
class Index < ActiveRecord::Base
	belongs_to :state_record

	def self.min(year)
		self.indices_for(year).map(&:index).min
	end

	def self.max(year)
		self.indices_for(year).map(&:index).max		
	end

	def self.indices_for(year)
		self.all.select { |idx_obj| idx_obj.year == year }
	end


end

app/models/state_record.rb
class StateRecord < ActiveRecord::Base
	has_many :indices
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/choropleth_controller.rb
class ChoroplethController < ApplicationController

	def view
	end

end

app/controllers/explanation_controller.rb
class ExplanationController < ApplicationController

	def show

	end

end

app/controllers/indices_controller.rb
class IndicesController < ApplicationController

	def min_max
		puts "ajax params: "
		min_max = [Index.min(params[:year].to_i), Index.max(params[:year].to_i)]
		puts min_max
		min_max
		render json: min_max
	end
end

app/controllers/state_records_controller.rb
class StateRecordsController < ApplicationController

	def get_record
		state_record = { 
			state: params[:state], 
			indices: StateRecord.find_by(state: params[:state]).indices
		}
		p state_record.inspect
		render json: state_record
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/choropleth/_commentary.html.erb
<div class="commentary">
<p>Single-Family Housing Price Indexes by State: 1991 to 2010</p>
<p>Index 1991, 1st quarter = 100. The index reflects average price changes in repeat sales or refinancings on the same properties. Since the data are for the fourth quarter, the index represents the annual percentage change in home values in the fourth quarter of the year shown relative to the fourth quarter of the previous year. The information is obtained by reviewing repeat mortgage transactions on single-family properties whose mortages have been purchased or securitized by either Fannie Mae or Freddie Mac.</p>
<p>Source: Federal Housing Finance Agency, Housing Price Index, 4th quarter 2010. See also <http://www.fhfa.gov>.<p>
<p>Internet Release Date: 9/30/2011</p>
<p>For more information http://www.fhfa.gov</p>
</div>

app/views/choropleth/view.html.erb
<div class="header">
	<h3>Single-Family Housing Price Index 1991 - 2010</h3>
	<p>Choose a year and two (different) colors to load price index data. The first color represents the lowest index in the country for that year, and the second represents the highest. Click on any state for a chart of price index data over the entire period 1991 - 2010.</p>
	<div class="options">
		<% year_options = (1991..2010).to_a.map { |year| [year.to_s, year.to_s] } %>
		<%= label_tag(:year, 'Year: ') %>     
		<%= select_tag(:year, options_for_select(year_options)) %><br>
		<% color_options = %w(white red orange yellow green blue violet black).map { |color| [color, color] } %>
		<%= label_tag(:color, 'Color Gradient (low index to high): ') %>
		<%= select_tag(:low_color, options_for_select(color_options)) %>
		 to 
		 <% color_options << color_options.shift %>
		<%= select_tag(:high_color, options_for_select(color_options)) %>
		<span id="explanation">
			<%= button_to 'Explanation, Challenges, etc.', explanation_path, method: 'get' %> 
		</span>
	</div>
</div>
<div id="choropleth_wrapper">
	
</div> 
<div id="loading_div"><img src="/img/spinner.gif"/></div>
<div id="modal_line_chart"></div>
<%= render 'commentary' %>
<a href="https://github.com/CalderWishne/price_index_visualizations"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://camo.githubusercontent.com/365986a132ccd6a44c23a9169022c0b5c890c387/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f7265645f6161303030302e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png"></a>

app/views/explanation/_explanation.html.erb
<p>Explanation</p>
	


<p>Challenges</p>
<p>
	Prior to this project, my only D3 experience consisted of computing vertices on a hexagonal grid. Creating the choropleth required me to really engage with D3 paths and geojson. I had also never used the NVD3 library before, so I was thrilled when the charts started appearing as I had imagined them. 
</p>
<p>
	Preparing the data files was interesting. 

<p>In The Icebox</p>
<ul>
	<li>Index vs. Year modal charts highlight the selected year. (Thought of this after the fetaure-freeze.)</li>
	<li>The chart for a given state compares its index for the selected year with the corresponding indices from adjacent states. (I tried to implement a many-to-many self-referential relation among the states and almost succeeded, but not quite. In an effort to keep the master branch clean and deployable, I implemented a feature-freeze earlier this evening. With more time I would have investigated the possibility of modeling adjacencies with a graph database.)
	<li>States with the highest and lowest index for a given year should be highlighted on the choropleth. (Thought of this after the feature-freeze.)<li>
</ul>	





</div>

app/views/explanation/show.html.erb
<%= button_to 'Home', root_path, method: 'get' %>
<h3>Explanation</h3>
	The price index dataset intrigued me because of the collapse of the housing bubble in 2008. Indeed, nearly every pop-up modal chart shows a sudden decline in the single-family housing price index around that time. I also thought that state-specific data would lend itself well to a choropleth, a D3 technique I'd been meaning to try. In the end, my two motivations conflicted a bit: the choropleth can show data for only one year at a time, masking any temporal influence. The pop-ups help, but I wish I had done more. See "In the Icebox" below. 

	Despite these misgivings, I am quite proud of my work. The Chloropleth highlights any correlations between price index and location, bringing to light several interesting features. For the most part, housing price inflation was more exaggerated in the western states. I don't know why this is, but perhaps it bears investigating. 

<h3>Challenges</h3>
<p>
	I didn't have to massage the price index data very much (unless you count converting CSV to JSON), but the geojson was another story. The states were in the wrong order, the data included puerto rico, and I had to try several different resolutions to achieve a decent loading-time without sacrificing detail.  
</p>
<p>
	Prior to this project, my only D3 experience consisted of computing vertices on a hexagonal grid. Creating the choropleth required me to really engage with D3 paths and geojson. I had also never used the nvD3 library before, so I was thrilled when the charts started appearing as I had imagined them. 
</p>
<p>
	Deploying to Heroku went smoothly at first, but I definitely had to troubleshoot. This project showed me the extreme usefulness of Heroku logs. 
</p>

<h3>In The Icebox</h3>
<ul>
	<li>One should be able to display data for different states and years simultaenously. I would like to collate the current pop-up charts in a reasonable way to more clearly illustrate time-dependence. </li>
	<li>Index vs. Year modal charts should highlight the selected year. (Thought of this after self-imposed fetaure-freeze.)</li>
	<li>The chart for a given state should compare that state's index for the selected year with the corresponding indices from adjacent states. (I tried to implement a many-to-many self-referential relation among the states and almost succeeded, but not quite. In an effort to keep the master branch clean and deployable, I implemented a feature-freeze earlier this evening. With more time, I would have investigated the possibility of modeling adjacencies with a graph database.)
	<li>States with the highest and lowest index for a given year should be highlighted on the choropleth. (Thought of this after the feature-freeze.)</li>
	<li>The year-selector feature should probably have a slider interface.</li>
</ul>	

app/views/layouts/_github_ribbon.html.erb
<a href="https://github.com/you"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://camo.githubusercontent.com/365986a132ccd6a44c23a9169022c0b5c890c387/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f7265645f6161303030302e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png"></a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Price Index Choropleth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= yield %>
</body>
</html>